# Generated by Django 5.1.7 on 2025-04-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('higherstudiesportal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
